Banner from blue to white
esa/torchquad pull request #42
Opened 2021-02-19 15:12 UTC by htoftevaag

Changed the banner (top left)  colour from blue to white

2021-03-05 17:21 UTC, GabrieleMeoni approved these changes

2021-03-05 17:22 UTC, GabrieleMeoni requested changes
Logo is fine, but some conflicts need to be solved before merging.

2021-03-10 15:44 UTC, htoftevaag commented
Fixed the conflict, the PR should now be ready to be merged.

2021-03-12 08:14 UTC, GabrieleMeoni approved these changes

2021-03-12 08:14 UTC, merged