Add VEGAS Placeholders
esa/torchquad pull request #53
Opened 2021-04-09 11:56 UTC by gomezzz

2021-04-09 13:29 UTC, htoftevaag requested changes
Please see my comments.

2021-04-09 13:29 UTC, htoftevaag commented on torchquad/integration/vegas.py
> +        self.results = []  # contains integrations results per iteration
"contains integrations results per iteration" -> contains integration results per iteration
or 
-> contains integration's results per iteration
or
-> contains integrations' results per iteration

2021-04-09 13:29 UTC, htoftevaag commented on torchquad/integration/vegas_map.py
> +    """The map used for vegas enhanced. Refer to https://arxiv.org/abs/2009.05112.
vegas -> VEGAS

2021-04-09 13:29 UTC, htoftevaag commented on torchquad/integration/vegas_stratification.py
> +    """The stratification used for vegas enhanced. Refer to https://arxiv.org/abs/2009.05112.
Same, vegas -> VEGAS

2021-04-15 08:08 UTC, gomezzz commented
I have added the requested changes.

2021-04-15 09:19 UTC, htoftevaag requested changes

2021-04-15 09:19 UTC, htoftevaag commented on torchquad/integration/vegas.py
> +    """Vegas Enhanced in torch. Refer to https://arxiv.org/abs/2009.05112.
Sorry for not noticing this the first time, but shouldn't it be `VEGAS Enhanced` here as well?

2021-04-15 12:03 UTC, merged